name: "${project.name}"
version: "${project.version}"
description: "${project.description}"
main: com.zachsthings.netevents.NetEventsPlugin
commands:
    netevents:
        description: status report on netevents
        usage: /<command>
        permission: netevents.status
